# Generated by Django 3.2.16 on 2022-10-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ref_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
