# Generated by Django 3.2.15 on 2022-10-07 00:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_email'),
        ('medical_report', '0004_totallcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absoluteleukocytecount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neutrophil', models.FloatField(blank=True, null=True)),
                ('lymphocyte', models.FloatField(blank=True, null=True)),
                ('monocyte', models.FloatField(blank=True, null=True)),
                ('eosinophil', models.FloatField(blank=True, null=True)),
                ('basophil', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
