# Generated by Django 3.2.15 on 2022-10-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_report', '0005_absoluteleukocytecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageadd',
            name='name',
        ),
        migrations.AlterField(
            model_name='imageadd',
            name='date',
            field=models.CharField(blank='True', max_length=255),
        ),
    ]
