# Generated by Django 3.2.16 on 2022-10-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_report', '0010_alter_imageadd_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageadd',
            name='date',
            field=models.DateField(),
        ),
    ]
