# Generated by Django 3.2.16 on 2022-10-13 09:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_email'),
        ('medical_report', '0012_alter_imageadd_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imageadd1',
            fields=[
                ('date', models.DateField()),
                ('image', models.ImageField(default='default.jpg', upload_to='blood/')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
