# Generated by Django 3.2.16 on 2022-10-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_report', '0013_imageadd1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imageadd1',
        ),
    ]
