# Generated by Django 3.2.16 on 2022-10-13 10:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medical_report', '0015_alter_imageadd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageadd',
            name='image_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='imageadd',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
