# Generated by Django 3.2.16 on 2022-10-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_report', '0016_auto_20221013_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageadd',
            name='date',
        ),
        migrations.AddField(
            model_name='imageadd',
            name='testdate',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
