# Generated by Django 3.2.16 on 2022-10-13 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medical_report', '0017_auto_20221013_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageadd',
            name='uploaddate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
