# Generated by Django 3.2.15 on 2022-10-14 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_email'),
        ('medical_report', '0018_imageadd_uploaddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(blank=True, max_length=255, null=True)),
                ('image_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('imageid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_report.imageadd')),
            ],
        ),
    ]
