# Generated by Django 3.2.15 on 2022-10-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_report', '0020_auto_20221016_1809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blood_report',
        ),
    ]
